[project]
name = "Dislaunch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pycairo>=1.27.0",
    "pydantic>=2.10.6",
    "pygobject>=3.50.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = ["ruff>=0.9.7"]
